export const ROUTES = {
  root: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  signUpWithEmail: '/sign-up-with-email',
  resetPassword: '/reset-password',
  newPassword: '/new-password',
  home: '/home',
  verifyEmail: '/verify-email',
  thankYou: '/thank-you',
  location: '/location',
  brand: '/brand',
  link: '/link',
  walkThrough: '/walk-through',
  notFound: '/404',
  categories: '/categories',
  account: '/account',
}
