export const chapters = [
  {
    title: '1. Acceptance and Scope of Terms',
    content: [
      '1.1 These terms of use including the privacy policy (together “Terms”) apply to visitors and registered users, i.e. those who list and offer a property on our website ("Landlord", "You", "Your") and/or those looking to book/rent a property from a landlord via the website ("Tenant", "You "," Your ").',
      '1.2. You understand and agree that these Terms apply between you and POP UP SHOPS and govern your access to, your use of and your registration on our Site and that you read, understood and accepted these Terms.',
      '1.3 We reserve the right, at our sole discretion, to change these Terms at any time. You must review these Terms on a regular basis to keep yourself informed of any changes. \n By using this Site, You agree that the posting of new or revised Terms (including the Booking Terms) on the Site shall constitute adequate and constructive notice to You of any and all revisions and changes. Continued use of the Service after any such changes or after explicitly accepting the new Terms upon logging into the Site shall constitute Your consent to such changes.',
      '1.4 POP UP SHOPS calculates the users is no charge for access to the website user or the insertion of a property on the website. However, if a lease agreement between tenants and landlords is completed through the use of our website and services, calculated POP UP SHOPS fees, which are further described in these terms and conditions and the booking conditions.',
      'In the event of any conflict between any provisions of the German and a translated version of these Terms and Conditions, the German version shall prevail. Any translation of these Terms of Use are complacency and translations for information purposes only.',
    ],
  },
  {
    title: '2. Platform',
    content: [
      '2.1 The Site merely is a platform that enables You and other Users (i.e. Landlords and Tenants) to connect and conclude rental transactions in respect of properties listed on the Site. POP UP SHOPS is not itself a party to any such rental transaction and is not a contracting agent or representative of any Landlord and disclaims all liability arising from or related to any such transactions to the fullest extent permitted by law.',
      "POP UP SHOPS' role is solely to facilitate the availability of the Site and Services for Users and to provide certain services related thereto. We do not purchase, buy-in, own, sell, provide, rent, sublet, control or manage nor can We contract in our own name for the provision of any property listed on the Site.",
      '2.2. Rental transactions are only binding among the concerned Landlords and Tenants, who are both solely and entirely responsible for their performance and POP UP SHOPS disclaims all liability arising from or in connection with such transactions.',
    ],
  },
  {
    title: '3. Eligibility and Accounts',
    content: [
      '3.1 By registering, You represent and warrant that: (a) You are at least eighteen (18) years old; and (b) the information You include as part of the registration process and thereafter is accurate and not misleading. You may act on behalf of an organisation or entity if You are authorised accordingly.',
      '3.2 Upon obtaining an Account, You shall have access to the Service and the functionality that We may establish and maintain from time to time and in our sole discretion. We may add, delete or change some or all of the Service provided for free as part of the Account at any time. You will be notified of any charges and given the option to continue use or to terminate Your Account.',
      '3.3 As a registered User, You further agree to update Your Personal Information (as defined in the Privacy Policy) if needed.',
      '3.4 You agree to allow POP UP SHOPS to contact You on Your email address or phone number with personal communications related to Your account, including but not limited to requests for booking, booking confirmation, notices and updates. You will be able to opt out of any future commercial communication at your convenience.',
      '3.5 POP UP SHOPS grants Users a limited, revocable, non-exclusive licence to access the Site to, as applicable, advertise properties and/or research, view or make legitimate inquiries to Users regarding their interest in particular properties for their personal use, all in accordance with these Terms ("Licence").',
      '3.6 Any other use of the Site is expressly prohibited. Importantly, this Licence does not include any right of collection, aggregation, copying or derivative use of the Site nor any right of use of data mining, robots, spiders or similar data gathering and extraction tools without our prior written permission; provided, however, that a limited exception from the foregoing exclusion is provided to general purpose internet search engines and non-commercial public archives that use tools to gather information for the sole purpose of displaying hyperlinks to the Site, provided they each do so from a stable IP address or range of IP addresses using an easily identifiable agent. “General purpose internet search engine” does not include a website or search engine or other service that provide classified listings or property rental advertisements, or any subset of the same, or which is in the business of providing property rental services.',
      '3.7 The following are grounds for immediate termination of an Account:',
      'a. Posting of false, outdated, misleading information;\n b. Posting information that in our sole discretion is inappropriate to our Users (including, but not limited to obscene, libelous, slanderous or similarly inappropriate postings); \n c. Publication of information in breach of the policies published on the Site;\n d. Distribution of unsolicited commercial messages (“spam”) through Your Account or any other action that imposes an unreasonable large load on our infrastructure. At our option and without further notice, We (or our suppliers) may use anti-spam technologies that may terminate Your messages without delivering them or prevent messages from reaching You.',
    ],
  },
  {
    title: '4. Your Content',
    content: [
      '4.1 Content, as used in these Terms, includes all text, photos, videos, files, reviews, postings, news, sounds or any other material ("Content").',
      '4.2 You understand and agree that you are solely responsible for the Content or any other information that you posted on, transmitted through, linked from the Service or otherwise uploaded to the Website and You agree that We are only acting as a passive conduit for Your online distribution and publication of Your Content. We reserve the right (but not the obligation) to take any action with respect to Your Content if we believe that it may create liability for Us or may cause Us to lose the services of our ISPs or other suppliers.\n You represent and warrant that Your Content and any content You request to receive (directly or indirectly): (a) shall not infringe any copyright, patent, trademark, trade secret, or other proprietary right or right of publicity or privacy; (b) shall not violate any law or regulation; (c) shall not be defamatory or libellous; (d) shall not be obscene or contain pornography; (e) shall not include incomplete, false or inaccurate information about Yourself or any information about any other individual; and (f) shall not contain any viruses, Trojan horses, worms, time bombs, cancelbots or other computer programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information.',
      '4.3 You understand and agree that, by posting Content on the Site, You automatically grant Us, and You represent and warrant that You have the right to grant POP UP SHOPS, an irrevocable, perpetual, non-exclusive, fully paid, worldwide licence to use, copy, perform, display, adapt, modify, distribute, to have distributed and promoted said Content, and to grant and authorise sublicences of the foregoing. Furthermore, by posting Content on the Site, You automatically grant POP UP SHOPS all rights necessary to prohibit any subsequent aggregation, display, copying or exploitation of Content on the Site by any party for any purpose.',
      '4.4 The Site provides unfiltered access to Content. You understand and agree that the Site only acts as a platform and that We disclaim all liability related to Content posted on the Site, whether arising under intellectual property laws, libel, privacy, obscenity, or otherwise. We cannot, nor do We undertake any obligation to, control the Content that is posted. By its very nature, the information on the Site is changed frequently, may be inaccurate and in some cases may be mislabelled or deceptively labelled. We do not make any representation or warranty, express or implied, as to the accuracy, timeliness, or completeness of such information, nor do We undertake to verify, update or correct such information. We recommend that You confirm all information You obtain from the Site as accurate and complete and up to date. We also do not make any representation or warranty, express or implied, regarding any posting or requests by Users. You agree that any agreement between You and such individual or organisation shall be solely on the terms negotiated and agreed by You and Your counterparty and shall be done at Your own risk.',
      "4.5 You understand and agree that POP UP SHOPS has no obligation to post any Content from You or anyone else. In addition, We may, in our sole discretion, edit, remove or delete any Content that You post or submit. In particular, We reserve the right to determine the final design, layout and functionality of our Site, which may involve the review, formatting and editing of such Content. In case You intentionally or negligently cause any loss or damage to POP UP SHOPS because of the design or positioning of such Content you are liable towards Pop Shops. You understand and agree to release POP UP SHOPS from any liability for any loss or damage resulting from the design or positioning of such Content, unless such loss or damage resulted from POP UP SHOPS' willful misconduct or negligence.",
    ],
  },
  {
    title: '5. Terms particular to Landlords',
    content: [
      '5.1 As a Landlord, you may create or add listings. You will be able to indicate the location, the features, the availability of the property and pricing; additionally, You may include certain terms or requirements which must be met by Tenants as part of any potential rental transaction relating to Your listed property ("House Rules"). \n All properties must have valid addresses in order to be featured in listings on the Site. Your listings will be made publicly available via the Site and Tenants will be able to book Your rental property via the Site based upon the information provided in Your listing. You, and not POP UP SHOPS, are solely responsible for determining the rental price to be displayed in Your listing and any additional charges (for example, cleaning fees) to be included or factored into such price (your “Landlord Fee”). You understand and agree that once a Tenant requests a booking of Your listed property, the rental rate You have set for such booking request may not be altered. As a Landlord, You acknowledge and agree that You are solely responsible for any and all of your listings of rental properties on our Site.',
      '5.2 You warrant, represent and undertake that \n a. all and any listings You place on Our Site relate to available space at an existing property; and \n b .You have all necessary rights and permissions, including without limitation, planning permission, or, if You are not the owner of such property, the express authorisation from the owner, to deal with the property, including creating listings related to it and offering it for rentals.',
      '5.3 Our Service to You as a Landlord shall include supporting and assisting you in listing, marketing, promoting and advertising Your property on our Site. However, as noted above, We cannot and do not in any way act as a contracting agent or representative for You as a Landlord, nor as a broker or insurer in each case, in relation to Your rental transactions which You conclude with Tenants via the Site. But we can and shall act as your disclosed agent or intermediary in Your name and on your behalf in relation to handling or managing payment collection processes involving advanced payment and cancellation transactions with Tenants, which processes are governed by the Booking Terms. Our Service to You as a Landlord in relation to the provision of information and email or messaging services shall also include assisting You in respect of communications with Tenants through the Site, for example, in receiving, notifying and forwarding to You any booking requests or enquiries made through the Site by a Tenant and in receiving and handling cancellation requests from Tenants.',
      '5.4 You acknowledge and accept that We do not consider that we act as a real estate broker generally in relation to the provision of our Site and/or our Service or in respect of Your actual rental transactions concluded with Tenants as We are not a party to such actual rental transactions and We do not buy-in, re-sell or provide space in our own name as mentioned in Section 2 above and Section 2 of the Booking Terms. Any necessary modifications may be made to these Terms as a consequence of this provision or part thereof applying.',
      '5.5 Our fees are calculated on the basis of the rental fee you specify for Your listed property ("Landlord Fee") or a listing fee respectively. You agree that we will charge and invoice a service fee for our Service to You as a Landlord in the event You conclude a rental transaction with a Tenant as a result of using our Site and Service. Where applicable, any applicable VAT or sales tax is also calculated and shown on the invoice for the Landlord. This Service Fee is based on a percentage (usually between 5% and 20%) of your Landlord Fee. In addition, we shall also collect an administrative fee of 5% based on the total of the Landlord Fee and the Service Fee. Where applicable, any applicable VAT or sales tax is also calculated and shown on the invoice for the Tenant. The fees as described herein (collectively, our "Fees") and any taxes shall be added by way of a mark up to the Landlord Fee and displayed to the Tenants in the Listing before booking and set out in the booking confirmation sent to the Tenant. In addition and at any time, both Landlord and Tenant can generate their respective PDF-invoice for a transaction in their account.',
      '5.6 Our Service to Landlords shall not include the collection of deposits or additional charges from Tentants that are not included or factored in your Landlord Fee. POP UP SHOPS shall not be responsible for administering or accepting a request or claim from You related to such additional charges or payments and disclaims any liability in this respect. Landlords will need to carry out a separate arrangement with Tentants in respect of such charges and expressly state in the listing of their property that additional charges in the form of a deposit or otherwise (for example, cleaning fees, security deposit and late checkout fees) are required separately from the Tenant (for example upon arrival or check-out) if such charges are not included or factored in the Landlord Fee.',
      '5.7 As a Landlord, You are solely responsible for honouring any booking confirmation sent to a Tenant and for supplying and making available and providing Your listed property on the Site to the Tenant on such terms, conditions, rules and restrictions as You have set and agreed with the Guest. As a Landlord, You acknowledge and agree that You are responsible for Your own acts and omissions and for the acts and omissions of any individuals (other than Tenants) who rent or are otherwise present at Your rental property. Each Landlord is solely responsible for compliance with laws, rules and regulations, including any tax and VAT requirements (see also the next provision below) and in respect of any conflict with or breach of rights of third parties. We recommend that Landlords obtain appropriate insurance for their rental properties listed on the Site, and where appropriate, require the Tenants to obtain adequate insurance.',
      '5.8 As a Landlord, You are solely responsible for determining your applicable Tax reporting requirements in consultation with your tax advisors. POP UP SHOPS cannot and does not offer Tax-related advice to any Users of our Site and Service. Additionally, please note that You are responsible for determining and/or paying any local VAT or similar indirect sales Taxes and/or for factoring in or including such VAT and taxes into your Landlord Fee or satisfying such obligations relating to applicable Taxes in adding a listing on our Site or in respect of our Fee as charged or invoiced to You or otherwise, particularly if You consider that you are in business in using the Site. You should in any event consult your tax advisor.',
      '5.9 Upon registering as a User as an intended Landlord, Landlords acknowledge and accept that POP UP SHOPS shall assume, and be entitled to assume, that You are in business/a taxable person/carrying on an economic activity and/or VAT registered, in the place/country where Your address details as provided to Us are located, unless and until You tell and confirm to POP UP SHOPS by email or otherwise that You consider that You are not in business etc. or that You are usually resident or spend most of Your time in another country. Landlords further accept and acknowledge that We may contact You to require details (acting reasonably) of Your VAT registration number (if any) or otherwise copies of reasonable commercial evidence or records, for example contracts, business letterheads, a commercial website address, publicity material, certificates from fiscal authorities, in each case, which You shall provide or procure to provide within your power or ability to do so. A digital certificate from a reputable organisation can also be accepted for this purpose.',
      '5.10 If Your listed property is requested by a Tenant via our Site, you will be required to either confirm or reject the Tenants’s request within 7 days of that request, after which the booking request shall automatically expire. If, as a Landlord, You confirm that listed property is available and a Tenant’s booking is subsequently accepted and confirmed by You through our Site, You will receive Your Tenant’s relevant contact details (including phone number) from Us and We will also forward Your contact details to the Tenant. Once such contact details have been provided, all communication including concerning details and information about the rental transaction should be direct between You and Your Guest through our Site as facilitated by our Service where required/applicable.',
      '5.11 Upon a booking confirmation, we shall collect the money from a Tenant, subject to a duty to transfer or account such monies – less our aforementioned fees - to You (provided always that You have honoured such booking), which we shall pay to You by bank transfer in the currency you have set for the relevant property. You acknowledge and agree that we shall be entitled to deduct and retain our Fees from such monies collected. We shall generally initiate the payment to You of all net monies collected from Tenants which are due to You within two Swiss business days (being days where banks are open in Switzerland) of the planned date of Your Tenant’s check-in at Your listed property (and We shall have no further commitment to You under these Terms), subject to any other arrangement as may be agreed between You and POP UP SHOPS. POP UP SHOPS reserves the right to pay You in installments if the duration of the lease exceeds 21 days. If You do not honour a booking, You may lose Your entitlement to Your Landlord Fee and We reserve the right to retain the corresponding funds collected in order to refund the Tenant as also referred to further in the Booking Terms.',
      '5.12 Tenants can cancel their booking at any time, but always accordingly to the cancellation policy that You have selected as a Landlord. In the event a Tenant cancels, We shall transfer to You the monies collected by Us from such Tenant, less our Fee, in accordance with Your selected cancellation policy.',
      '5.13 As a Landlord, You should not cancel a confirmed booking. If however, exceptional circumstances require You to cancel a booking, please notify Us at landlord@popupshops.ch for assistance in relation to Your communications with the Tenant. Please also refer to the Booking Terms in this respect in terms of refunds payable to Tenants.',
      '5.14 We reserve the right to cancel any booking at any time for security or fraud-protection purposes. This is generally due to our fraud-detection processes reporting a problem with the payment card submitted. In such cases the cancellation policy that you have selected will not apply and you will receive no payment for the cancelled booking.',
      '5.15 Payment processing services for Landlords and/or Service Providers on POP UP SHOPS are provided by Stripe and are subject to the Stripe Connected Account Agreement, which includes the Stripe Terms of Service (collectively, the “Stripe Services Agreement”). By agreeing to terms or continuing to operate as a Landlord and/or Service Provider on POP UP SHOPS, you agree to be bound by the Stripe Services Agreement, as the same may be modified by Stripe from time to time. As a condition of POP UP SHOPS enabling payment processing services through Stripe, you agree to provide POP UP SHOPS accurate and complete information about you and your business, and you authorize POP UP SHOPS to share it and transaction information related to your use of the payment processing services provided by Stripe.',
    ],
  },
  {
    title: '6. Limitation of Liability',
    content: [
      ' For Users based in Germany and Austria the following limitation of liability set out in Section 6(i) shall apply:',
      "(i) For slightly negligent breach of material contractual obligations – or “cardinal obligations” - POP UP SHOPS' liability shall be limited in the amount to the damage typically foreseeable at the time of the conclusion of the contract. Material contractual obligations (or “cardinal obligations”) are those obligations which put the User into exactly this legal position to which he shall be entitled pursuant to contents and purpose of the contractual terms as well as such obligations, whose performance only will make possible proper performance of the contract and on whose full compliance the User regularly relies and is entitled to rely.",
      'POP UP SHOPS accepts no liability for the slightly negligent breach of obligations other than those listed above. Otherwise the User’s statutory claims for damages remain unaffected unless they are limited by a contractual provision individually agreed by the parties. The aforesaid limitation of liability shall not apply in cases of mandatory statutory liability (in particular under the terms of the Product Liability Act (Produkthaftungsgesetz), malicious concealment of a defect, on assumption of a guarantee or culpable personal injury by POP UP SHOPS. The User undertakes to take appropriate steps to prevent and mitigate damage.',
      'For Users based in countries other than Germany and Austria the following limitation of liability set out in Section 6(ii) shall apply:',
      '(ii) The Content and all other material displayed on the Site is provided without any guarantees, conditions or warranties as to its accuracy. To the extent permitted by law, We hereby exclude: (i) all conditions, warranties and other terms which might otherwise be implied by statute, common law or the law of equity; and (ii) any liability for any direct, indirect or consequential loss or damage incurred by any User in connection with the Site, any websites linked to it and any Content and other materials posted on it including loss of income or revenue; loss of business; loss of profits or contracts; loss of anticipated savings; loss of data; and loss of goodwill, whether caused by tort (including negligence), breach of contract or otherwise, even if foreseeable.',
      'This does not affect our liability for death or personal injury arising from our negligence, nor our liability for fraudulent misrepresentation, nor any other liability which cannot be excluded or limited under applicable law. Although these Terms of Use require Users to provide accurate information (see section 6 above under Your Content), We do not attempt to confirm, and do not confirm, any User’s purported identity. You are responsible for determining the identity and suitability of others who You contact via the Site or allow into Your listed property. We will not be responsible for any damage or harm resulting from Your interactions with other Users.',
    ],
  },
  {
    title: '7. Release and indemnity',
    content: [
      '7.1 By using the Site and/or Services, You agree that any legal remedy or liability that You seek to obtain for actions or omissions of other users or other third parties will be limited to a claim against the particular user or users or other third parties who caused You harm at the exclusion of POP UP SHOPS to the fullest extent permitted by law.',
      '7.2 You shall indemnify POP UP SHOPS (and its officers, employees, representatives, agents, subsidiaries and successors), against any liability, damage, loss, expense, claim or cost (including reasonable legal fees and costs) suffered by POP UP SHOPS arising from or in connection with : (a) infringement in or by any of Your content of any third party rights; (b) any damage, loss, expense, claim or other cost suffered by any user relating to Your content, or any property you might offer or book via our site; or (c) breach of section 3.6 and 3.7 (account restrictions), section 4 (your content) or section 5.2 (terms of use particular to landlords).',
    ],
  },
  {
    title: '8. Data privacy',
    content: [
      'Your privacy is very important to Us. By accepting this Agreement, You expressly consent to certain disclosures of Your Personal Information (as defined in our Privacy Policy) to Us and the other Users, as described in our Privacy Policy, which is incorporated to these Terms by reference.',
    ],
  },
  {
    title: '9. Termination',
    content: [
      'In the event of a material breach by You of these Terms or the Booking Terms including but not limited to fraud by You, We may, in our discretion and without liability to You: (a) terminate Your access to Our Service; (b) deactivate or delete any of your Accounts and all related information and files in such Accounts as well as Your Content; and (c) bar Your access to any of such files or Service. In addition, We reserve the right at any time and without any prior notice to remove or disable access to a listing of any property on the Site which in Pop Up Shops’ sole discretion considers to be objectionable, in violation or breach of these Terms or Booking Terms, or otherwise harmful to the Site and/or Services.',
    ],
  },
  {
    title: '10. Invalidity',
    content: [
      'If any provision or part of a provision, of these Terms is found by any court or authority of competent jurisdiction to be unlawful, otherwise invalid or unenforceable, such provision or part-provision will be struck out of these Terms and the remainder of these Terms will apply as if the offending provision or part-provision had never been agreed.',
    ],
  },
  {
    title: '11. Assignment',
    content: [
      'You may not transfer any of Your rights or obligations under these Terms without our prior written consent. We may transfer any of our rights or obligations under these Terms without Your prior written consent.',
    ],
  },
  {
    title: '12. Applicable Law and Jurisdiction',
    content: [
      '12.1 These Terms and all matters arising out of or relating to these Terms (including non-contractual disputes or claims and their interpretation) shall be governed by the laws of Switzerland to the extent that such law is not overridden by applicable mandatory law applying to You.',
      '12.2 Any claim or dispute arising out of or relating to these Terms shall (including non-contractual disputes or claims and their interpretation) shall be subject to the non-exclusive jurisdiction of the courts of the city of Zurich.',
    ],
  },
  { title: '13. Questions', content: ['If you have any questions about these Terms, please contact POP UP SHOPS'] },
]
